version: '3.8'

services:
  backend:
    build: ./backend
    container_name: securelink-backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DJANGO_ALLOW_ASYNC_UNSAFE=true
    depends_on:
      - redis

  frontend:
    build: ./frontend
    container_name: securelink-frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://backend:8000/api
    depends_on:
      - backend

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
