# Generated by Django 5.2.7 on 2025-10-08 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maestros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('maestro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maestros.maestro')),
            ],
        ),
    ]
